site_name: Omeka S User Manual
theme: 'readthedocs'
pages:
    - 'Home': 'index.md'
    - 'Admin Dashboard': 'admin-dashboard.md'
    - 'Glossary': 'glossary.md'
    - 'Searching': 'search.md'
    - 'Sites': 
        - 'Sites Management': 'sites/sites.md'
        - 'Site Settings': 'sites/site_settings.md'
        - 'Pages Management': 'sites/site_pages.md'
        - 'Navigation': 'sites/site_navigation.md'
        - 'Resources': 'sites/site_resources.md'
        - 'Theme Selection': 'sites/site_theme.md'
        - 'Theme Settings': 'sites/site_themesettings.md'
    - 'Resources':
        - 'Items': 'content/items.md'
        - 'Item Sets': 'content/item-sets.md'
        - 'Media': 'content/media.md'
    - 'Vocabularies': 'content/vocabularies.md'
    - 'Resource Templates': 'content/resource-template.md'
    - 'Users': 'users.md'
    - 'Modules': 
        - 'Modules Management': 'modules/modules.md'
        - 'Individual Modules Documentation':
            - 'Collecting': 'modules/collecting.md'
            - 'CSV Import': 'modules/csvimport.md'
            - 'Custom Vocab': 'modules/customvocab.md'
            - 'DSpace Connector': 'modules/dspaceconnector.md'
            - 'Fedora Connector': 'modules/fedoraconnector.md'
            - 'Mapping': 'modules/mapping.md'
            - 'Metadata Browse': 'modules/metadatabrowse.md'
            - 'Omeka2 Importer': 'modules/omeka2importer.md'
            - 'Sharing': 'modules/sharing.md'
            - 'Zotero Import': 'modules/zoteroimport.md'
    - 'Jobs': 'jobs.md'
    - 'Manage Settings': 'settings.md'
    - 'Error Logging': 'errorLogging.md'